version: "3"
services:
  recorder:
    build: .
    user: nginx
    volumes:
      - ./config:/usr/src/app/config
      - ./log:/usr/src/app/log
      - /srv/ddrecorder:/usr/src/app/data
    restart: always
